### ISSUE TITLE
Measurement averaging across multiple experiments (for k-fold cross validation) 

### ISSUE THREAD

**Issue by leej35** [comet-ml/issue-tracking#118]
For K-fold cross-validation, it would be good to select multiple experiments (on the same experiment but different fold number) and compute their averaged metrics and also its variances.

**Comment by pierthodo** [comment]
+1 for this. This could be useful for deep reinforcement learning where you need to average performance over several random seeds.

**Comment by gidim** [comment]
Thanks for the feedback @leej35 and @pierthodo. Would a single point average/stats be sufficient here? Sounds like in @pierthodo you want to generate an averaged curve as well?

**Comment by pierthodo** [comment]
Yes averaged curve with variance bands  would be ideal. Something similar to tsplot in seaborn.

**Comment by leej35** [comment]
I think besides variance, the 95% confidence intervals (both high and low) are also very good stats!

**Comment by tesslerc** [comment]
+1 this.
If possible, the ability to create a graph based on a custom function.
Variance, alpha-confidence intervals, min/max/mean

Also allow this to be performed on the smoothed graphs would be great :)

**Comment by backpropper** [comment]
Can you update the status on this? This would one of the biggest improvements to the GUI

**Comment by gidim** [comment]
We received numerous requests for better chart functionality / features
both here and from customers. Instead of implementing everything which
isn't feasible we are working on a new chart editor that will allow you to
implement any custom logic and much much more. We're very excited about
this feature and have been working on it for the last two months. We expect
to have first version in beta in the next 30 days.

Thanks for your patience!

**Comment by backpropper** [comment]
Oh thanks for update! Looking forward to the new chart editor.

**Comment by Nimrod007** [comment]
We have introduced comet panels which allows you to code any chart . please see panels docs: https://www.comet.ml/docs/user-interface/panels/
