### ISSUE TITLE
More explanation on PCS format is needed in doc 

### ISSUE THREAD

**Issue by leej35** [comet-ml/issue-tracking#121]
In documentation (https://www.comet.ml/docs/python-sdk/Optimizer/#optimizerset_params), explanation about PCS format is not in detail. So it is hard to understand what each part means (especially the last term.) So would you provide a more detailed explanation on the PCS format?

**Comment by ceceshao1** [comment]
Hello @leej35 - thanks for your feedback on the docs! 

We do have an example at the top for the optimizer + the PCS format (here: https://www.comet.ml/docs/python-sdk/Optimizer/), but I do see your point 👍 

We'll add an example or put in a clear link to the optimizer example at the top in the `set_params` section. In the meantime, let me know via slack DM if you need any help running the optimizer.

**Comment by ceceshao1** [comment]
Hi @leej35 - we've actually added in an entire section about the PCS format in our documentation here: https://www.comet.ml/docs/python-sdk/pcs-file/

I'll be closing the issue since it has been resolved. Feel free to re-open if you feel the docs do not answer your questions about the PCS format! Thanks for submitting 👍
