### ISSUE TITLE
[Feature Request] Tagging Experiments

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#147]
Hi There!

It'd be super nice to add tags to an experiment and be able to filter by those tags. 

The reason for me is because I run many variations (multiple changes and single changes) of similar experiments. I think I can express this variation with tags. With Tensorboard, I expressed this by giving experiments increasingly longer naming schemes... 

Thanks!

**Comment by ceceshao1** [comment]
@PetrochukM - this feature request is in progress. We will update you when the feature is ready in production. You can also check out our [Release Notes](https://www.notion.so/cometml/Comet-ml-Release-Notes-93d864bcac584360943a73ae9507bcaa)

**Comment by ceceshao1** [comment]
@PetrochukM - you can now add tags to your experiments (see more details in the [Release Notes](https://www.notion.so/cometml/Comet-ml-Release-Notes-93d864bcac584360943a73ae9507bcaa#625b308b024b4afe87766889c2e31c60)).

Give it a try and let us know your feedback! Closing this issue because the requirement has been completed
