### ISSUE TITLE
[Feature Request] Audio Tab

### ISSUE THREAD

**Issue by PetrochukM** [comet-ml/issue-tracking#149]
Hi There!

Coming from Tensorboard, I'm looking to replace all the features I used and relied on in Tensorboard. One those tabs is the "audio" tab. It's the same as the graphics tab but displays audio elements.

Thanks!

**Comment by PetrochukM** [comment]
NOTE: Already talked to Gideon about a workaround with the log_html element.

**Comment by Nimrod007** [comment]
Hey @PetrochukM - in the new asset tab, would it be beneficial to have a play audio ? (similar to preview image)

**Comment by ceceshao1** [comment]
@PetrochukM - there is now an audio play button in the Asset Tab. You will be able to play + hear the audio upon selecting an audio asset! 

Please make sure to upgrade to the latest version of Comet.ml to use this feature. Reach out to the team on slack if you have any questions!

**Comment by psmaragdis** [comment]
FYI, on Safari the sounds do not seem to play (they play on Chrome)

And useful as this functionality is, I find the tensorboard/wandb way to archive audio data is much more user-friendly and manageable (i.e. an audio player with a steps popup selector). It would be great to have that option in Comet.ml, even more so if it can show up in the visualizations so that I don't have to search for the sounds in the specific experiment (also having a popup in the player to switch between experiments would be nice too, that would allow for some easy A/B testing).

**Comment by gidim** [comment]
Hi @psmaragdis  - we're working on building this. Would you be willing to jump on a a quick call to  tell us what you'd like to have there? feel free to shoot me an email product@comet.ml

thanks!
