### ISSUE TITLE
Automatic loading of image summaries

### ISSUE THREAD

**Issue by lleewwiiss** [comet-ml/issue-tracking#228]
Currently, comet nicely loads all of your `tf.summary.scalar` and places them on the dashboard. It would be very useful if this functionality was extended to other summary types, ideally `tf.summary.image` and loaded automatically in the graphics tab.

**Comment by gidim** [comment]
Hi @lleewwiiss  - thanks for suggesting this!

We had an internal discussion on this and decided not to auto-log these image summaries. The main reason is because people can report huge images which we then need to broadcast / host. The concern is that people won't be aware that they're trying to send gigabytes of data and that would also slow down their metrics reporting.
Hopefully you can just add `log_image()` calls whenever you need this?
