### ISSUE TITLE
Add Rest API support for filtering experiments

### ISSUE THREAD

**Issue by zwade** [comet-ml/issue-tracking#282]
For us specifically, it would be helpful to filter results from the `/rest/v1/experiments` endpoint by tag value. Currently, to find experiments with a given tag we have to scan over every single experiment. More broadly, being able to filter by other fields (name, description, etc.) might be helpful too, but we care specifically about tags.

**Comment by dsblank** [comment]
That is an interesting idea! We will explore this possibility.

**Comment by neighthan** [comment]
@gidim I have the same experience, though I'm usually filtering by parameters instead of tags. It would be nice to replicate as much of the query capabilities of the website as possible. I could see this either being a mini-language for the queries which are passed as strings like `"experimentKey begins with 521"` or perhaps a sequence of tuples like `(param_name, query_type, maybe_query_args)` like `("experimentKey", "is null")` or `("experimentKey", "begins with", "521")`.  A mini-language would probably make it easier to compose conditions with logical operators (e.g. `cond1 AND (cond2 OR cond3)`, but I don't think that's supported on the website, so I don't know if you'd want to support that through the API or not? If you went with the latter option, you could perhaps create a handful of `filter` functions to make it easier to remember the right words for each operator. Maybe something like

```python
from comet_ml import filters

my_filter = filters.compose(
    filters.begins_with("experimentKey", "521"),
    filters.between("accuracy", 0.8, 0.9),
)
```

In the end, this would probably just be constructing a query string anyway. The interface doesn't matter much to me; I just thought I'd throw out a couple of ideas in case it helps. Filtering every single experiment in Python ourselves will probably always offer the greatest flexibility, but I'd be glad to have a querying API that supports most use cases and makes things faster (on projects with thousands of experiments, it's quite slow to filter each experiment on my end).

If you do think about adding more querying abilities to the API than the website supports, I'd be glad to have an `"is in"` operator. This could also be created easily enough if we can use OR to compose filters.

**Comment by dsblank** [comment]
Yes, indeed that would be a great way to do it. Thanks for the ideas!

**Comment by backpropper** [comment]
Yes this is quite useful and would really appreciate if you make this available soon!

**Comment by gidim** [comment]
Thanks for the feedback.  We're looking into the best way to expose the query builder API. The good news is that we can probably expose richer functionality than the UI.

**Comment by backpropper** [comment]
it'd also would be great to have a filter based on some "saved views" or "saved queries" via REST API

**Comment by dsblank** [comment]
You can now use filters in the Python API. See: https://staging.comet.ml/docs/python-sdk/API/#apiquery
