### ISSUE TITLE
Group Experiments and Plot Aggregate Metrics

### ISSUE THREAD

**Issue by KaleabTessera** [comet-ml/issue-tracking#283]
The visualizations on the experiment page only use the data from the experiments in the current view (50/100 experiments per page).
![image](https://user-images.githubusercontent.com/10942061/62530679-49ad7400-b841-11e9-83d6-6e6ebd2e6f6c.png)

I would like to run these visualizations on all the experiment data, is this possible?

**Comment by gidim** [comment]
Hi @KaleabTessera,
Thanks for reporting. The reason we limit the number of experiments you can visualize is both from a browser performance perspective and usability. After a certain amount of points/lines/bars the charts become unreadable. 

Usually you can create a simple query that will filter some of the experiments that are clearly "not interesting". This could be dead runs, runs with terrible performance etc. 

If you think we're missing a use case please let us know! Otherwise i'll close this issue.

**Comment by KaleabTessera** [comment]
Those points make sense @gidim . For me, I usually run each experiment about 10 times, so if I want to plot 15 experiments in a graph (150 seperate runs), I can't do that. 

Maybe allowing groupings to be plotted would be handy. For example, group data by a certain field and then specify some sort of agg like mean, and then be able to plot that.

**Comment by andresespinosapc** [comment]
This also would be great for experiments that are very sensible to random initialization. I would love to group multiple experiments and get the mean an variance between them.

**Comment by gidim** [comment]
This is now available on beta. If you're interested in trying it out please join our slack channel: chat.comet.ml and ask for beta access!

**Comment by Nimrod007** [comment]
this is possible with comet panels, see https://www.comet.ml/docs/user-interface/panels/
