### ISSUE TITLE
comet upload fail since `/tmp/xx/experiment.json` not found

### ISSUE THREAD

**Issue by ZENGXH** [comet-ml/issue-tracking#309]
My environment variable `COMET_OFFLINE` points to a local directory. But when I try to upload when the experiment is running by
``` 
COMET_OFFLINE_DIRECTORY=/path/to/comet_offline/ comet upload /path/to/comet_offline/...zip
``` 
I get error: 
```
COMET INFO: Attempting to upload '/scratch/gobi1/xiaohui/code/comet_offline/5cdeb31ae03d4f11a38217dd2ece8c2b.zip'...
COMET ERROR:     Upload failed
Traceback (most recent call last):
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/comet_ml/offline.py", line 585, in main_upload
    filename, api_key, force_reupload
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/comet_ml/offline.py", line 556, in upload_single_offline_experiment
    sender = OfflineSender(api_key, unzipped_directory, force_reupload=force_reupload)
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/comet_ml/offline.py", line 360, in __init__
    self._read_experiment_file()
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/comet_ml/offline.py", line 383, in _read_experiment_file
    with open(join(self.offline_dir, "experiment.json")) as experiment_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwoes39st/experiment.json'
COMET INFO: Number of uploaded experiments: 0
COMET INFO: Number of failed experiment uploads: 1

```

I can't fine the json file in the offline dir either. When and where will this file be created?

**Comment by florpi** [comment]
Same problem here! The json file doesn't seem to be saved

**Comment by dsblank** [comment]
@florpi Let's take these one at a time. Can you send me (doug@comet.ml) a copy of a zip file that fails? The second issue: how are you setting your COMET_API_KEY?

**Comment by florpi** [comment]
Email sent :) Thanks!

**Comment by dsblank** [comment]
I think we figured the issue out.... looks like the original experiment failed, and thus the zip file is incomplete. This can happen, for example, if an external process outside of Python kills the script before it can finish writing the zip file. By the way, more recent versions of comet_ml have some enhancements to try to help make sure this can't happen.

**Comment by xelange** [comment]
Hello, 

does the OfflineExperiment work differently from the "normal" Experiment? I would expect that the zip-File is populated with the logged data continuously, so that I can also upload it whenever I want to see the current progress of the training / optimization process. However, either I messed something up or it seems that one can only upload the zip-file after the training / optimization is finished. Does anyone have experience with it? 

The scenario here is that I do not have internet access on the compute nodes and therefore store OfflineExperiments locally. From time to time, I'd like to upload it to the webinterface using one of the login nodes of the cluster, which have internet access. 

Thanks in advance.
