### ISSUE TITLE
Log scale chart plots the log of values instead of changing the axes

### ISSUE THREAD

**Issue by TevenLeScao** [comet-ml/issue-tracking#338]
Hi,

I am currently encountering two related issues with log-scale plots.

1. When plotting with both axes in log scale, there still is a shadow of the linear plot in the visualization that makes it harder to see the log plot, as in the screenshot below (darker orang eis what I'm plotting, lighter orange is the parasitic plot):

![image](https://user-images.githubusercontent.com/26709476/76219897-d7f23a00-6216-11ea-982b-e2d773c169d7.png)

Of course, one can zoom into the log graph, but that can take quite a bit of time as that region is so much smaller.

2. Even after zooming, the numbers are meaningless as the log of the metric is plotted, rather than plotting the original metric on a logarithmic axis.

Changing the axes to be a proper log scale rather than plotting the log of the values on a linear scale would deal with both issues. It is also what people usually mean by log scale plot, so shouldn't that be the default behaviour instead of the current one ? I am not sure whether that is a feature request or a bug report.

**Comment by mrvadims** [comment]
Thank you for reporting the issue.  We are looking into it and will update you shortly.

**Comment by mrvadims** [comment]
We have updated the behavior of the "log scale" transformation to scale the axis, instead of applying the log function to the data itself.  The old behavior is still available under "log(value)" transformation.  The latest version is up in the Production environment.

![image](https://user-images.githubusercontent.com/2479256/76346874-17cf2500-62dc-11ea-8d39-ae843fd97658.png)
