### ISSUE TITLE
[Feature request] Listening to audio in confusion matrix

### ISSUE THREAD

**Issue by dorekhov1** [comet-ml/issue-tracking#342]
It would be great if it'd be possible to listen to audio examples, when analyzing confusion matrix (similar to how you can see images now).

**Comment by dsblank** [comment]
That would be very cool! Adding to our list. Thanks!

**Comment by dsblank** [comment]
As a workaround, you can add links to the confusion matrix example selection so that they will take you to the sounds (which could be assets at Comet, or some other place).

For more details, see the "index_to_example" function on these pages:

* https://www.comet.ml/docs/python-sdk/Comet-Confusion-Matrix/
* https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_confusion_matrix
