### ISSUE TITLE
[feature request] Support best, worst and median in query filter

### ISSUE THREAD

**Issue by Manolomon** [comet-ml/issue-tracking#361]
Hi, It would be great to have an additional option in the query filter to automatically select the best, worst, and median experiment. This would be helpful for optimization algorithms, being able to plot only the desired experiments in the convergence plot.

**Comment by dsblank** [comment]
@Manolomon That is an interesting idea! It might be hard to implement in a general way, because you are probably measuring many metrics (accuracy, loss, etc).

But you could easily do this yourself for whichever metric you pick. You could use the Comet API and tag each experiment with your own tagging system, and use that in the filter.

**Comment by Manolomon** [comment]
Thank you so much. I'm closing the issue.

BR
