### ISSUE TITLE
`Experiment.get_metric` Return a value that does not exist. 

### ISSUE THREAD

**Issue by khirotaka** [comet-ml/issue-tracking#373]
When I wrote the following code, I expected it to return either an error or none, but in fact `Experiment` object returned the value at training time.

```python
from comet_ml import Experiment

experiment = Experiment()

for epoch in range(10):
    with experiment.train():
        experiment.log_metric("avg_acc", 0.5)

    with experiment.validate():
        print(experiment.get_metric("avg_acc"))
```

* comet.ml v3.1.15
* python 3.7

**Comment by dsblank** [comment]
@khirotaka Thanks for the question. Some points about your code:

* the `Experiment.get_metric()` is a simple function for just getting the last sent value
* it does not respect the context
* you probably want to use an `APIExperiment` to actually query the logged values, with the full name

Here is an example:

```
In [1] : from comet_ml import Experiment, APIExperiment 
    ...: import time 
    ...:  
    ...: experiment = Experiment() 
    ...: api_experiment = APIExperiment(previous_experiment=experiment.id, cache=False) 
    ...:  
    ...: for epoch in range(10): 
    ...:     with experiment.train(): 
    ...:         experiment.log_metric("avg_acc", 0.5) 
    ...:      
    ...:     time.sleep(3) 
    ...:  
    ...:     print(api_experiment.get_metrics("train_avg_acc")) 
    ...:      
    ...:                                                                                                                                                      
```
The print will show:

```
[{'metricName': 'train_avg_acc', 'metricValue': '0.5', 'timestamp': 1596807246237, 'step': None, 'epoch': None, 'runContext': 'train', 'offset': 20}]
```

The sleep is used to give the server time to process the logging.

You can also use `api_experiment.get_metrics_summary()` to get just the min/max/current value of a metric rather than getting all logged values.

**Comment by khirotaka** [comment]
@dsblank Thanks for the reply !

It's exactly what I wanted to do!
It was helpful. Thank you!
