### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#397]
It would be nice to have a dark/night mode. Currently for this I use the Dark Reader chrome extension, but it doesn't handle well the plots.

**Comment by dsblank** [comment]
Passing on this suggestion to the team. Thanks for the idea!

**Comment by rabyj** [comment]
Would also appreciate greatly, any update? (or dark reader that works with the website)

**Comment by rabyj** [comment]
@dsblank  Having any update from the team before closing would be appreciated.

**Comment by dsblank** [comment]
@rabyj Sure! The issue is on our list of feature requests, internal tracking number EXT-1387. Thanks for the followup.

**Comment by plutonium-239** [comment]
Hello, is there any update on this? Would really love this too, my eyes are quite sensitive and existing dark theme extensions don't handle the graphs well.
Since comet appears to be using plotly for charts, it should be even better since plotly has a lot of theming inbuilt, so wouldn't have to do much there I hope

**Comment by dsblank** [comment]
@plutonium-239, update! While we are not planning on tackling this in the short term it is something that we plan on implementing in the future. Stay tuned!

**Comment by calculating** [comment]
would pay for this. Need to be able to check run status in the middle of the night without pain.
