### ISSUE TITLE
Support nested dictionaries of parameters

### ISSUE THREAD

**Issue by alkamid** [comet-ml/issue-tracking#41]
This is a feature request. It would be useful if nested dictionaries were supported as parameters, e.g.
```
params = {
   'model_params': {
       'input_size': [32, 32, 3],
       'filters': 4
       }
   'training_params': {
       'batch_size': 16,
       'lr': 3e-4
   }
}
```

Currently the lowest level of the dictionary is lost, and only the keys are saved in Comet.ml dashboard, e.g. `model_params = ['input_size', 'filters']`.

**Comment by gidim** [comment]
Thanks for the feedback! We'll look into this. 

In the meantime one option to get around this is using the prefix:
```
    for name, param_dic in params.items():
        experimente.log_multiple_params(param_dic, prefix = name)

```

**Comment by gidim** [comment]
Hi @alkamid, did the above code example solves this issue?

**Comment by alkamid** [comment]
It was intended as a feature request, so I guess you should decide whether you are happy for the users to use this workaround or you'd rather deal with nested dictionaries on Comet's side.

**Comment by dsblank** [comment]
I don't think we can automatically solve this because some users may think of the dict as the value, but others, like you, think of it as a nested list of values.

As @gidim mentioned, you can pick the level that you want to get values with:

```python
for name, param_dic in params.items():
        experiment.log_parameters(param_dic, prefix=name)
        # or further expand/log
```

or store the whole dict as a value:

```python
experiment.log_parameter("params", str(params))
```
or the current default behavior which logs the keys.

Thanks for reporting!
All are valid possibilities.
