### ISSUE TITLE
Retrive metrics from an existing experiment

### ISSUE THREAD

**Issue by khush3** [comet-ml/issue-tracking#421]
Hello!

I am trying to retrieve parameters (and some metrics) that have been logged previously using the ExistingExperiment class. However, while trying to do so, using the `get_parameter` throws KeyError. I can see that the `metrics` and `parameters` do not carry any value for the instance of the ExistingExperiment class I created. 

Thank you so much!

Code snippet:
```python
from comet_ml import ExistingExperiment
exp = ExistingExperiment('dummy-api-key, 'dummy-experiment-key')

exp.get_parameter('lr')
```

Output:
```
KeyError: 'lr'
```
Further, I see `{}` on printing `exp.params`. I also tried toggling parameters passed in the ExistingExperiment used to alter/destroy previously logged information, which did not help.

**Comment by dsblank** [comment]
@khush3 Thanks for the question! The `experiment.get_parameter()` is currently used to get the parameters logged by the current existing experiment. In order to get a parameter logged previously by another experiment instance, you'll need to use the `APIExperiment.get_parameters_summary("lr")` which would work something like:

```python
>>> exp = ExistingExperiment('dummy-api-key', 'dummy-experiment-key')
>>> api = API('dummy-api-key')
>>> api_exp = api.get_experiment_by_id(exp.id)
>>> api_exp..get_parameters_summary("lr")
         {'name': 'batch_size',
          'valueMax': '120',
          'valueMin': '120',
          'valueCurrent': '120',
          'timestampMax': 1558962363411,
          'timestampMin': 1558962363411,
          'timestampCurrent': 1558962363411}
```

Sorry for the confusion! We're working on unification of the experiment interfaces.

**Comment by khush3** [comment]
Thank you!
