### ISSUE TITLE
export to csv / json

### ISSUE THREAD

**Issue by Nimrod007** [comet-ml/issue-tracking#5]
enable users to export data into csv file

**Comment by ceceshao1** [comment]
@soaxelbrooke / @avterekhov / @corriebar -  just an update here. **We've released v1 of our REST API** (see the documentation [here](https://www.comet.ml/docs/rest-api/endpoints/)). 

I'm keeping this issue open since we don't support direct-to-csv format, but thought the REST API might be helpful to the three of you since you reacted to this GH issue! 

You can see the full REST API issue here: https://github.com/comet-ml/issue-tracking/issues/47

**Comment by AlexPiche** [comment]
Hi, I think it could be a useful feature when collaborating with non-technical people.

**Comment by benbetze** [comment]
would definitely be helpful for quick manipulation.

**Comment by system123** [comment]
Can this not be added to the frontend plots? Like Tensorboards export button which exports the chart data as CSV. This is critical in being able to truly evaluate metrics (such as plotting Learning rate vs Loss) to determine the best LR rate.

**Comment by leej35** [comment]
Hopefully, I think at first, simply exporting current experiments table on a certain view (query) should be enough for us to handle experiments results in other tools such as Excel for further tasks (e.g., making experiment result plots).

**Comment by leej35** [comment]
For those who seek intermediate solution, you can use chrome extension that helps you to export any table in the web to Excel: https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop?hl=en

**Comment by jdegange** [comment]
I continue to believe this would be a helpful feature. If I had more time...I would prototype something to suggest. :) Very helpful extension above, thanks.

**Comment by jdegange** [comment]
> For those who seek intermediate solution, you can use chrome extension that helps you to export any table in the web to Excel: https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop?hl=en
I continue to believe this would be a helpful feature. If I had more time...I would prototype something to suggest. :) Very helpful extension above, thanks.

**Comment by dvirginz** [comment]
I agree this cool help a lot.

**Comment by AidanConnelly** [comment]
There's a Comet ML panel available for this now

**Comment by dsblank** [comment]
Thanks @AidanConnelly ! Indeed, in the new Panel Gallery you'll find a user-contributed first draft of a "Export Experiment Data":

![Screenshot from 2020-05-04 14-50-11](https://user-images.githubusercontent.com/168568/81002169-cb552100-8e16-11ea-8051-b33053eaf246.png)

You'll also find the source code there. If you make it better, or it doesn't do exactly what you want, let us know!

**Comment by Mateusmsouza** [comment]
**7 years later** and this feature is still not available?
There are some workarounds like REST API, Comet ML panel, and export Data as a JSON in line chart panel (which seems to export a incomplete version...) this is a really important feature and IMO should be crystal clear how to export full data on the user interface.

**Comment by MaxHeuillet** [comment]
Hello, I have 1500 experiments and i want to compile the parameters and final results in a csv file to identify which set-up performs best. I am stuck because "export csv" button only allows to export the experiments visible on a single page (25, 50, 100). Same for the panel proposed on this forum. Finally, the code API only offers get_parameters_summary() which is not convenient to manipulate to create a table that compiles all the experiments. This feature would be much appreciated! Thanks
