### ISSUE TITLE
Possibility to Duplicate a Project or Transfer Default View Templates Between Projects

### ISSUE THREAD

**Issue by tristanryerparke** [comet-ml/issue-tracking#538]
## Is your feature request related to a problem? Please describe.
I've split my research into several projects, but most of the research I'm doing is similar and is tracked in a similar way. Therefore I would like to have access to my configured views on a scale beyond the project level. 
I know its possible to move an experiment between projects, but the default project view, or any project view does not move with it. 

## Describe the solution you'd like
The simplest solution in my mind would be an option in the project browser to duplicate a project, and for the newly created project to have the same default view as the base project. 

## Describe alternatives you've considered
Another option would be to have a way to copy views between Projects. 

## Additional context
Projects are a nice way to group experiments, but for multiple projects in the same vein which require similar methods of display, it would be nice to be able to transfer those display methods and not re-build them each time.

Thanks!!

**Comment by dsblank** [comment]
@tristanryerparke , did you know that you can share views (both project and experiment) between projects? You don't have to rebuild them.

**Comment by tristanryerparke** [comment]
No sorry, I didn't know it was possible.
Can you point me to some documentation or explain how here?
Thanks,
T

**Comment by dsblank** [comment]
@tristanryerparke , you can save a "view" (at either the Project or Experiment level) and then reuse it in other projects (by view name). You can also have a default view for each and every project/experiment view. 

Documentation:
* https://www.comet.com/docs/v2/guides/comet-dashboard/more-in-projects/#create-project-views

The same is true for experiment views.

**Comment by tristanryerparke** [comment]
@dsblank I'm noticing that I can access views from other projects only in the multi-experiment view. See the comparison of these two images:
When viewing a single experiment or diff view:
<img width="1677" alt="Screenshot 2024-03-07 at 5 18 10 PM" src="https://github.com/comet-ml/issue-tracking/assets/57774376/409f4b44-9f25-46bc-a2b2-15e26083915d">
When viewing the project hompage:
<img width="1657" alt="Screenshot 2024-03-07 at 5 20 01 PM" src="https://github.com/comet-ml/issue-tracking/assets/57774376/39f1851b-ab57-45f5-8d09-5dc650499a5d">
Am I potentially running up against a limitation of the community version?
Thanks,
T

**Comment by dsblank** [comment]
No, I don't believe that we have any limitations like that in the Comet app. I think it was a design choice, as there are many more experiments than there are projects. But I will check. If you were to make a request, is it that you would like to re-use views from other experiments from other projects?

**Comment by bdawg** [comment]
I have this same issue, it would be great if this could be reopened. 

As with the original submission, the problem is that when a view is created for a Single Experiment Page, it does not seem to be possible to reuse that same view for a single experiment page in another project. (Unlike the Project Page views, which _can_ be reused in a different project).

This is a big roadblock, as significant effort can be invested in creating a view for a single experiment page, but then if conducting a similar set of experiments later in a different workspace it seems that you need to rebuild the single experiment page from scratch. This situation occurs often, e.g.: a hyperparameter optimisation is performed, resulting in a very large number of experiments which are contained in a single project. A new hyperparameter optimisation (for a slightly different architecture) is then to be performed later, but if placed in a new workspace (to keep the results separate) the single experiment view must be remade from scratch.

Is there a way to transfer a single experiment view between projects? If bnot through the UI, is there a workaround via the API, etc?
